    ---
    - hosts: vm1
      become: true
      vars:
        vm1_ip: "YOUR_VM1_IP_ADDRESS"
      tasks:
        - name: Install Zabbix Agent
          apt:
            name: zabbix-agent
            state: present
        - name: Copy Zabbix Agent configuration file
          template:
            src: zabbix_agentd.conf.j2
            dest: /etc/zabbix/zabbix_agentd.conf
          notify: restart zabbix-agent

    - hosts: vm2
      become: true
      vars:
        vm2_ip: "YOUR_VM2_IP_ADDRESS"
      tasks:
        - name: Install Zabbix Agent
           apt:
            name: zabbix-agent
            state: present
        - name: Copy Zabbix Agent configuration file
          template:
            src: zabbix_agentd.conf.j2
            dest: /etc/zabbix/zabbix_agentd.conf
          notify: restart zabbix-agent

    handlers:
       - name: restart zabbix-agent
         service:
            name: zabbix-agent
            state: restarted
