    ---
    - hosts: vm1
      become: true
      vars:
        vm1_ip: "YOUR_VM1_IP_ADDRESS"
      tasks:
        - name: Install Nginx
          apt:
            name: nginx
            state: present
        - name: Copy index.html file
          template:
            src: index.html.j2
            dest: /var/www/html/index.html
        - name: Ensure Nginx is running
          systemd:
            name: nginx
            state: started
            enabled: yes

    - hosts: vm2
      become: true
      vars:
        vm2_ip: "YOUR_VM2_IP_ADDRESS"
      tasks:
        - name: Install Nginx
          apt:
            name: nginx
            state: present
        - name: Copy index.html file
          template:
            src: index.html.j2
            dest: /var/www/html/index.html
        - name: Ensure Nginx is running
          systemd:
            name: nginx
            state: started
            enabled: yes
